### ISSUE TITLE
Rename tool

### ISSUE THREAD

**Issue by eliasnaur** [orijtech/consensuswarn#6]
`statediff` is the perfect name the tool that implements https://github.com/cosmos/cosmos-sdk/issues/13404. I suggest renaming this tool to something else, say `statepr`, `statepatch`, `consensuswarn`.

Thoughts, @odeke-em ? Not terribly important, but good to have solved before releasing chain halt tool.

**Comment by odeke-em** [comment]
Thank you @eliasnaur for raising this important question! consensuswarn is very prime for the functionality, good stuff! Let's change it to consensuswarn

**Comment by eliasnaur** [comment]
Of course, this issue can also be solved by coming up with an even better name for the chain halt debugging differ.

**Comment by odeke-em** [comment]
Your instincts are sharp! If we use consensuswarn as the name here we shall even be more directed towards a nicer name for the chain halt debugger, which we can even use the full name for and abbreviate perhaps as "chdb" like "gdb" which stands for "GNU Debugger"
